- id: golines
  name: golines
  description: A golang formatter that fixes long lines.
  entry: golines
  args: [-w, .]
  types: [go]
  language: golang
  pass_filenames: false
  additional_dependencies: ['golang.org/x/tools/cmd/goimports@v0.17.0']
