name: lint
on:
  push:

permissions:
  contents: read

jobs:
  golangci:
    name: golines lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: false
      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          install-mode: binary
          skip-cache: true
