name: lint
on:
  push:

permissions:
  contents: read

jobs:
  golangci:
    name: golines lint
    # we need ubuntu 20.04 because golines needs
    # to run on hosts with older glibc versions
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          install-mode: binary
          skip-cache: true
